/**
 * Furbish response phrasebook, transcribed verbatim from
 * Furby::Command::Dictionary (Hacksby project, MIT-licensed):
 * https://github.com/iafan/Hacksby/blob/master/lib/Furby/Command/Dictionary.pm
 *
 * That file's own header credits this text to the official Hasbro Furby
 * Android app. It's 352 short phrase mappings (protocol response
 * code -> English + Furbish text) documenting what Furby says when it emits
 * a given response command — functional protocol documentation, generated
 * mechanically from the upstream file via a parsing script, not hand-typed.
 *
 * Two ids (102, 291) were defined twice in the source Perl hash; Perl hash
 * literals keep the last assignment, so this does too.
 */
export interface PhrasebookEntry {
  id: number
  english: string
  furbish: string
}

export const PHRASEBOOK: readonly PhrasebookEntry[] = [
  { id: 0, english: 'Me like.', furbish: 'Kah toh-loo.' },
  { id: 1, english: 'Me like you.', furbish: 'Kah toh-loo oo-nye.' },
  { id: 2, english: 'Upside down!', furbish: 'Oo-tye nah-bah!' },
  { id: 3, english: 'Listen.', furbish: 'Ay-ay-lee-koo.' },
  { id: 4, english: 'Singing time.', furbish: 'Wee-tee toh-toh.' },
  { id: 5, english: 'Big joke!', furbish: 'Dah loo-loo!' },
  { id: 6, english: 'More talk.', furbish: 'Koh-koh noo-noo.' },
  { id: 7, english: 'Yes. Thank you.', furbish: 'Ee-tay. Dah-kah-oo-nye.' },
  { id: 8, english: 'Me like talk!', furbish: 'Kah toh-loo noo-noo!' },
  { id: 9, english: 'Talk big fun!', furbish: 'Noo-noo dah doo-ay.' },
  { id: 10, english: 'Yes no yes no.', furbish: 'Ee-tay boo ee-tay boo.' },
  { id: 11, english: 'Good food!', furbish: 'Ee-day ah-tah!' },
  { id: 12, english: 'More! More! More!', furbish: 'Koh-koh! Koh-koh! Koh-koh!' },
  { id: 13, english: 'Good morning!', furbish: 'Dah-ay-loh-oo-tye!' },
  { id: 14, english: 'Good game!', furbish: 'Ee-day doo-ay-loo-lah!' },
  { id: 15, english: 'Me see you.', furbish: 'Kah ay-ay oo-nye.' },
  { id: 16, english: 'Me love you.', furbish: 'Kah may-may oo-nye.' },
  { id: 17, english: 'Love friend!', furbish: 'May-may noo-lah!' },
  { id: 18, english: 'Big happy.', furbish: 'Dah noo-loo.' },
  { id: 19, english: 'Pet more.', furbish: 'Ah-may koh-koh.' },
  { id: 20, english: 'Big noise!', furbish: 'Dah bah-boo!' },
  { id: 21, english: 'Please hug me.', furbish: 'Doo-moh may-lah kah.' },
  { id: 22, english: 'Huh? Good morning.', furbish: 'Doo? Dah-ay-loh-oo-tye.' },
  { id: 23, english: 'Little noise.', furbish: 'Dee bah-boo.' },
  { id: 24, english: 'Tickle.', furbish: 'Nee-tye.' },
  { id: 25, english: 'Noise!', furbish: 'Bah-boo!' },
  { id: 26, english: 'Happy.', furbish: 'Noo-loo.' },
  { id: 27, english: 'Hug Me', furbish: 'May-lah Kah.' },
  { id: 28, english: 'Hey! No!', furbish: 'Hey! Boo!' },
  { id: 29, english: 'Me very happy, yeah!', furbish: 'Kah mee-mee noo-loo, wah!' },
  { id: 30, english: 'Me like. Again please.', furbish: 'Kah toh-loo. Koh-koh doo-moh.' },
  { id: 31, english: 'Uh-oh! Me no like.Uh-oh!', furbish: 'Kah no toh-loo.' },
  { id: 32, english: 'Me scared!', furbish: 'Kah dah-boh-bay!' },
  { id: 33, english: 'Me!', furbish: 'Kahhh!' },
  { id: 34, english: 'Me down!', furbish: 'Kah nah-bah!' },
  { id: 35, english: 'Me Me Me!', furbish: 'Kah kah kahhhh!' },
  { id: 36, english: 'No feel good!', furbish: 'Boo koo-doh e-day!' },
  { id: 37, english: 'Yeah! Yes!', furbish: 'Wah! Ee-tay!' },
  { id: 38, english: 'Dance!', furbish: 'Noh-lah!' },
  { id: 39, english: 'Me like dance.', furbish: 'Kah toh-loo noh-lah.' },
  { id: 40, english: 'Like, dance baby!', furbish: 'Tay, noh-lah bay-bee!' },
  { id: 42, english: 'No joke.', furbish: 'Boo loo-loo.' },
  { id: 43, english: 'JokeJokeJokeJoke!', furbish: 'LooLooLooLooLoo!' },
  { id: 44, english: 'Genius!', furbish: 'Dah-way!' },
  { id: 45, english: 'Pretty noise!', furbish: 'Ee-kah bah-boo!' },
  { id: 46, english: 'Big no!', furbish: 'Dah-boo!' },
  { id: 47, english: 'Me hungry!', furbish: 'Kah Ay-tay!' },
  { id: 48, english: 'No hungry!', furbish: 'Boo ay-tay!' },
  { id: 49, english: 'Me no happy.', furbish: 'Kah boo noo-loo.' },
  { id: 50, english: 'Me very hungry!', furbish: 'Kah mee-mee ay-tay!' },
  { id: 51, english: 'Please, hungry!', furbish: 'Doo-moh, ay-tay!' },
  { id: 52, english: 'Please talk.', furbish: 'Doo-moh noo-noo.' },
  { id: 53, english: 'Me tired.', furbish: 'Kah way-loh.' },
  { id: 54, english: 'Where are you?', furbish: 'Oo-nye doo?' },
  { id: 55, english: 'Funny talk.', furbish: 'Doo-loo noo-noo.' },
  { id: 56, english: 'Yeah, yeah, yeah?!', furbish: 'Wah, wah, wah?!' },
  { id: 57, english: 'Over, over, dizzy, me change!', furbish: 'Oo-bah, oo-bah, ay-way, kah boo-tay!' },
  { id: 58, english: 'Like singing!', furbish: 'Toh-loo wee-tee!' },
  { id: 59, english: 'Like, me LIKE!', furbish: 'Tay, kah TAY!' },
  { id: 60, english: 'Like, me hear you!', furbish: 'Tay, mah ay-ay-lee-koo oo-nye!' },
  { id: 61, english: 'Like, listen!', furbish: 'Tay, ay-ay-lee-koo!' },
  { id: 62, english: 'Me dance!', furbish: 'Kah noh-lah!' },
  { id: 63, english: 'Hmm? Okay!', furbish: 'Doo? Oh-kay!' },
  { id: 64, english: 'Huh? What? No!', furbish: 'Huh? Doo? Boo!' },
  { id: 65, english: 'No! Me dance!', furbish: 'Boo! Kah noh-lah!' },
  { id: 66, english: 'What? What? Whaaaa!!!?', furbish: 'Doo? Doo? Doooooo!!!?' },
  { id: 67, english: 'Wasssssupppp, buddy!', furbish: 'Dooooo Ooooooo-tye, noo-lah!!!!' },
  { id: 68, english: 'Shake, baby!', furbish: 'Koo-bah, bay-bee!' },
  { id: 69, english: 'Me beautiful!', furbish: 'Kah ee-kah!' },
  { id: 70, english: 'Me beautiful diamond!', furbish: 'Kah ee-kah ay-koo!' },
  { id: 71, english: 'Yeah yeah yeah talk!', furbish: 'Wah wah wah noo-noo!' },
  { id: 72, english: '…happy, yeah yeah, yeah yeah!', furbish: 'Shana noo-loo mah, shana wah wah moo-loo nah!' },
  { id: 73, english: 'Dance time.', furbish: 'Noh-lah toh-toh.' },
  { id: 74, english: 'Dance monster, like like, dance, buddy buddy, buddy, monster, like like, happy', furbish: 'Noh-lah moh-moh tay tay noo-lah noo-lah noo-lah moh-moh tay tay noo-loo.' },
  { id: 75, english: 'OMG! Good sound!', furbish: 'Oh-kah-tee! Ee-day lee-koo!' },
  { id: 76, english: 'Like, blah blah blah!', furbish: 'Tay, blah blah blah!' },
  { id: 77, english: 'Beautiful, baby!', furbish: 'Ee-kah, bay-bee!' },
  { id: 78, english: 'What\'s up?', furbish: 'Doo-oo-tye?' },
  { id: 79, english: 'Finally.', furbish: 'Oo-tah-toh-toh.' },
  { id: 80, english: 'Finally! Yeah!', furbish: 'Oo-tah-toh-toh! Yeah!' },
  { id: 81, english: 'Funny dance.', furbish: 'Doo-loo noh-lah.' },
  { id: 82, english: 'Good play!', furbish: 'Ee-day loo-lay!' },
  { id: 83, english: 'Play, yeah.', furbish: 'Loo, wah.' },
  { id: 84, english: 'Party time, baby!', furbish: 'Dah-noh-lah, bay-bee!' },
  { id: 86, english: 'Good sound!', furbish: 'Ee-day lee-koo!' },
  { id: 87, english: 'More good sound!', furbish: 'Koh-koh ee-day lee-koo!' },
  { id: 88, english: 'Watch me! Watch me!', furbish: 'Ay-ay kah!' },
  { id: 89, english: 'Yay! Whassup?', furbish: 'Yay! Doo-oo-tye?' },
  { id: 90, english: 'Yay! Me love dance!Yay!', furbish: 'Kah may-may noh-lah!' },
  { id: 91, english: 'What\'s up? You dance!', furbish: 'Doo-oo-tye? Oo-nye noh-lah!' },
  { id: 92, english: 'Dance! Dance! Dance! Dance!', furbish: 'Noh-lah! Noh-lah! Noh-lah! Noh-lah!' },
  { id: 93, english: 'Party time! Yea!', furbish: 'Daaah-nohhhh-lahhhhh! Wah!' },
  { id: 94, english: 'Life is dance!', furbish: 'Tee noh-la!' },
  { id: 95, english: 'Party time!', furbish: 'Dah-noh-lah!' },
  { id: 96, english: 'Me like music!', furbish: 'Kah toh-loo ee-kah-lee-koo!' },
  { id: 97, english: 'You dance!', furbish: 'Oo-nye noh-lah!' },
  { id: 98, english: 'You happy?', furbish: 'Oo-nye noo-loo?' },
  { id: 99, english: 'No! You party monster!', furbish: 'Boo! Oo-nye dah-no-lah moh-moh!' },
  { id: 100, english: 'Funny!', furbish: 'Doo-loo!' },
  { id: 101, english: 'Good joke!', furbish: 'Ee-day loo-loo!' },
  { id: 102, english: 'You funny.', furbish: 'Oo-nye doo-loo.' },
  { id: 103, english: 'No funny!', furbish: 'Boo doo-loo!' },
  { id: 104, english: 'Me monster!', furbish: 'Kah moh moh! Kah moh moh!' },
  { id: 105, english: 'Yay! You me talk.Yay!', furbish: 'Oo-nye kah noo-noo.' },
  { id: 106, english: 'Monster noise', furbish: 'Moh-moh bah-boo' },
  { id: 107, english: 'Dance monster!', furbish: 'Noh-lah moh-moh!' },
  { id: 108, english: 'Talk monster!', furbish: 'Noo-noo moh-moh!' },
  { id: 109, english: 'Yeeehaaa! You big monster!', furbish: 'Yeeehaaa! Oo-nye dah moh-moh!' },
  { id: 110, english: 'You look funny.', furbish: 'Oo-nye ay-ay doo-loo.' },
  { id: 111, english: 'Help!', furbish: 'Ah-noo!' },
  { id: 112, english: 'Finally! Hungry!', furbish: 'Oo-tah-toh-toh! Ay-tay!' },
  { id: 113, english: 'Like, Dance monster! Yeah!', furbish: 'Tay, noh-lah moh-moh! Wah!' },
  { id: 114, english: 'Food.', furbish: 'Ah-tah.' },
  { id: 115, english: 'No pet!', furbish: 'Boo ah-may!' },
  { id: 116, english: 'No like!', furbish: 'Boo toh-loo!' },
  { id: 117, english: 'No touch!', furbish: 'Boo ah!' },
  { id: 118, english: 'Me talk monster!', furbish: 'Kah noo-noo moh-moh!' },
  { id: 119, english: 'Me dance monster!', furbish: 'Kah Noh-lah moh-moh!' },
  { id: 120, english: 'Very good.', furbish: 'Mee-mee ee-day.' },
  { id: 121, english: 'Ok! Ok! Good! Yes!', furbish: 'Oh-kay! Oh-kay! Ee-Day! Ee-tay!' },
  { id: 122, english: 'Life genius!', furbish: 'Tee dah-way!' },
  { id: 123, english: 'Hey! Big no!Hey!', furbish: 'Dah boo!' },
  { id: 124, english: 'Me dizzy! Feed!', furbish: 'Kah ay-way! Ah-tah!' },
  { id: 125, english: 'Oh me genius, love dance, oh me genius…', furbish: 'Oh kah dah-way dee dee doo doo may-may noo-lah oh kah dah-way' },
  { id: 126, english: 'Feed me!', furbish: 'Ah-tah kah!' },
  { id: 127, english: 'Listen, listen, look listen, ooh sound, oh baby…', furbish: 'Ay-ay-lee-koo, ay-ay-lee-koo, ay-ay ay-ay-lee-koo, ooh lee-koo, oh, bay-bee…' },
  { id: 128, english: 'Oooh, you no good, good me genius, genius, genius, genius baby!', furbish: 'Oooh, oo-nye boo ee-day, ee-day kah dah-way, dah-way, dah-way, dah-way bay-bee!' },
  { id: 129, english: 'So funny!', furbish: 'Doh doo-loo!' },
  { id: 130, english: 'Music, baby!', furbish: 'Ee-kah-lee-koo, bay-bee!' },
  { id: 131, english: 'Ahhh Big Genius!', furbish: 'Ahhh Dahhh Dahh-wayyyy!' },
  { id: 132, english: 'Ohhhh myyyy goshhhh!', furbish: 'Ohhhh-kahhhh-teeeee!' },
  { id: 133, english: 'Kiss, baby!', furbish: 'May-tah, bay-bee!' },
  { id: 134, english: 'Me no healthy!', furbish: 'Kah boo koo-doh!' },
  { id: 135, english: 'Like, no way!', furbish: 'Tay, dah-boo!' },
  { id: 136, english: 'Yeah! Dude!', furbish: 'Wah! Deeee-dohhhh!' },
  { id: 138, english: 'Whoaaaa!', furbish: 'Whoaaaa!' },
  { id: 139, english: 'Oy! Huh?', furbish: 'Oy! Doo?' },
  { id: 140, english: 'Me big dance!', furbish: 'Kah dah noh-lah!' },
  { id: 141, english: 'Little dance!', furbish: 'Dee noh-lah!' },
  { id: 142, english: 'Watch me dance!', furbish: 'Ay-ay kah noh-lah!' },
  { id: 143, english: 'Dance! Yeah!', furbish: 'Noooh-Laaah! Wah!' },
  { id: 144, english: 'Me tired. More food!', furbish: 'Kah way-loh. Koh-koh ah-tah!' },
  { id: 145, english: 'Look good me, good sound, good sound, good sound…', furbish: 'Ay-ay ee-day kah, ee-day lee-koo, ee-day lee-koo, ee-day lee-koo…' },
  { id: 146, english: 'No like game!', furbish: 'Boo toh-loo doo-ay-loo-lah!' },
  { id: 147, english: 'You pull!', furbish: 'Oo-nye ah-loo!' },
  { id: 148, english: 'Yes! Uh-huh!', furbish: 'Ee-tay! Uh-huh!' },
  { id: 149, english: 'Like, OK!', furbish: 'Tay, oh-kay!' },
  { id: 150, english: 'Like, really? REALLY???', furbish: 'Tay, doo? DOO???' },
  { id: 151, english: 'Ahhh Big Genius!', furbish: 'Ahhh Dahhh Dahh-wayyyy!' },
  { id: 152, english: 'Yes! Yes! Yes!', furbish: 'Ee-tay! Ee-tay! Ee-tay!' },
  { id: 153, english: 'Ha! Dude!', furbish: 'Ha! Dee-doh!' },
  { id: 154, english: 'Thank you.', furbish: 'Dah-kah-oo-nye.' },
  { id: 157, english: 'Life good upside down.', furbish: 'Tee ee-day oo-tye nah-bah.' },
  { id: 158, english: 'Me happy.', furbish: 'Kah noo-loo.' },
  { id: 159, english: 'Life good!', furbish: 'Tee ee-day!' },
  { id: 160, english: 'Dude! Dude good friend.', furbish: 'Dee-doh! Dee-doh ee-day noo-lah.' },
  { id: 161, english: 'Ha! Dude!', furbish: 'Ha! Dee-doh!' },
  { id: 162, english: 'Love you, dude!', furbish: 'May-may oo-nye, dee-doh!' },
  { id: 163, english: 'Genius talk!', furbish: 'Dah-way noo-noo!' },
  { id: 164, english: 'Me like friend.', furbish: 'Kah toh-loo noo-lah.' },
  { id: 165, english: 'Me tough!', furbish: 'Kah tay-boo-koo!' },
  { id: 166, english: 'Me happy dude.', furbish: 'Kah noo-loo dee-doh.' },
  { id: 167, english: 'No fun.', furbish: 'Boo doo-ay.' },
  { id: 168, english: 'Very very very very fun!', furbish: 'Mee-mee mee-mee mee-mee mee-mee doo-ay!' },
  { id: 169, english: 'Me big dude.', furbish: 'Kah dah dee-doh.' },
  { id: 170, english: 'More joke.', furbish: 'Koh-koh loo-loo.' },
  { id: 171, english: 'Tickle!', furbish: 'Nee-tye!' },
  { id: 172, english: 'Huh? You eat me?', furbish: 'Doo? oo-nye ay-tay kah?' },
  { id: 173, english: 'Okay, uncle...', furbish: 'Oh-kay, oo-kah...' },
  { id: 174, english: 'Play Play Play Play Play!', furbish: 'LooLooLooLooLooooo!' },
  { id: 175, english: 'Ticke me! Now!', furbish: 'Nee-tye kah! Nee-way!' },
  { id: 176, english: 'Oh, very very!', furbish: 'Ohhh, mee-mee mee-mee!' },
  { id: 178, english: 'Whassssssupppppp!', furbish: 'Dooooo-ooooooo-tye!' },
  { id: 179, english: 'Me dizzy.', furbish: 'Kah ay-way.' },
  { id: 180, english: 'No dance.', furbish: 'Boo noh-lah.' },
  { id: 181, english: 'Dance? Really?', furbish: 'Noh-lah? Doo?' },
  { id: 182, english: 'Sweet! Uh-huh! Party!', furbish: 'Nee-may! Uh-huh! Dah-no-lah!' },
  { id: 185, english: 'More! More!', furbish: 'Koh-koh! Koh-koh!' },
  { id: 187, english: 'Me like tickle!', furbish: 'Kah toh-loo nee-tye!' },
  { id: 189, english: 'Help! Me scared... NOT!', furbish: 'Ah-noo! Me dah-boh-bay...KAH-LOO-LOO!' },
  { id: 190, english: 'Dude. What\'s up?', furbish: 'Dee-doh. Doo-oo-tye?' },
  { id: 191, english: 'Monster! Help!', furbish: 'Moh-moh! Ah-noo!' },
  { id: 192, english: 'You think me funny?', furbish: 'Oo-nye way kah doo-loo?' },
  { id: 195, english: 'Please.', furbish: 'Doo-moh.' },
  { id: 196, english: 'Dizzy!', furbish: 'Ay-way!' },
  { id: 197, english: 'Me dizzy.', furbish: 'Kah ay-way.' },
  { id: 198, english: 'Dizzy! Dizzy!', furbish: 'Ay-way! Ay-way!' },
  { id: 199, english: 'Me no hungry.', furbish: 'Kah boo ay-tay.' },
  { id: 202, english: 'More play!', furbish: 'Koh-koh loo-lay!' },
  { id: 204, english: 'Uh-oh.', furbish: 'Uh-oh.' },
  { id: 206, english: 'Like, when talk?', furbish: 'Tay, doo noo-noo?' },
  { id: 208, english: 'Yeah?', furbish: 'Doo?' },
  { id: 209, english: 'Yes! Uh-huh!', furbish: 'Ee-tay! Uh-huh!' },
  { id: 210, english: 'Yeah! Hug time!', furbish: 'Wah! May-lah toh-toh!' },
  { id: 212, english: 'When talk?', furbish: 'Doo noo-noo?' },
  { id: 213, english: 'Hmm? Like, why hug?', furbish: 'Doo? Tay, doo may-lah?' },
  { id: 214, english: 'Oh yeah!', furbish: 'Ohhhh wah!' },
  { id: 215, english: 'No talk, no love!', furbish: 'Boo noo-noo, boo may-may!' },
  { id: 217, english: 'Like, me dizzy.', furbish: 'Tay, kah ay-way.' },
  { id: 218, english: 'You no good!', furbish: 'Oo-nye boo ee-day!' },
  { id: 219, english: 'You no listen.', furbish: 'Oo-nye boo ay-ay-lee-koo.' },
  { id: 220, english: 'Where friend?', furbish: 'Doo noo-lah?' },
  { id: 221, english: 'Love it!', furbish: 'Dah-may-may!' },
  { id: 223, english: 'Oh!', furbish: 'Oh!' },
  { id: 224, english: 'Oh! Me like! Yeah! Yeah! Yeah!Oh!', furbish: 'Kah toh-loo! Wah! Wah! Wah!' },
  { id: 225, english: 'Yeah! Yeah! Yeaaaahhh!', furbish: 'Wah! Wah! Waaaaaaahhhh!' },
  { id: 228, english: 'Boring…', furbish: 'Boo-doo-ay…' },
  { id: 238, english: 'Dizzy sounds!', furbish: 'Ay-way lee-koo!' },
  { id: 239, english: 'Noisy song.', furbish: 'Bah-boo wah-tee.' },
  { id: 242, english: 'Like, you like song?', furbish: 'Tay, oo-nye toh-loo wah-tee?' },
  { id: 243, english: 'No more noise!', furbish: 'Boo koh-koh bah-boo!' },
  { id: 244, english: 'Huh? Oh! You play!', furbish: 'Doo? Oh! Oo-nye loo-lay!' },
  { id: 245, english: 'Why joke?', furbish: 'Doo loo-loo?' },
  { id: 246, english: 'Play game?', furbish: 'Loo doo-ay-loo-lah?' },
  { id: 247, english: 'Hey! You funny?', furbish: 'Hey! Oo-nye doo-loo?' },
  { id: 248, english: 'Hey! No more joke.', furbish: 'Hey! Boo koh-koh loo-loo.' },
  { id: 249, english: 'Love tickle!', furbish: 'May-may nee-tye!' },
  { id: 250, english: 'Sweet shake, baby!', furbish: 'Nee-may koo-bah, bay-bee!' },
  { id: 251, english: 'You move me, uh-huh!', furbish: 'Oo-nye noh-bah kah, uh-huh!' },
  { id: 255, english: 'Me see!', furbish: 'Kah ay-ay!' },
  { id: 256, english: 'No way!', furbish: 'Daahhhh-boooo!' },
  { id: 258, english: 'No way! Like, get out!', furbish: 'Dah-boo! Tay, bye-bye!' },
  { id: 261, english: 'Like, me like! Like, to say like! Like!', furbish: 'Tay, kah toh-loo! Tay, noo-noo tay! Tay!' },
  { id: 262, english: 'Like, you little talk! Me big talk!', furbish: 'Tay, oo-nye dee noo-noo! Kah dah noo-noo!' },
  { id: 263, english: 'Talk talk talk talk!', furbish: 'Noo-noo noo-noo noo-noo noo-noo!' },
  { id: 264, english: 'Talk more!', furbish: 'Noo-noo koh-koh!' },
  { id: 265, english: 'Talk more! Talk more!', furbish: 'Noo-noo koh-koh! Noo-noo koh-koh!' },
  { id: 266, english: 'You talk pretty, like love song!', furbish: 'Oo-nye noo-noo ee-kah, tay may-may wah-tee!' },
  { id: 267, english: 'Like, friends love talking.', furbish: 'Tay, noo-lah may-may noo-noo.' },
  { id: 268, english: 'Like, good hug.', furbish: 'Tay, ee-day may-lah.' },
  { id: 269, english: 'Like, holding and talking!', furbish: 'Tay, ah koh noo-noo!' },
  { id: 270, english: 'OMG!', furbish: 'Oh-kah-tee!' },
  { id: 271, english: 'Like, yes!', furbish: 'Tay, ee-tay!' },
  { id: 273, english: 'Talking is life.', furbish: 'Noo-noo tee.' },
  { id: 274, english: 'You genius!', furbish: 'Oo-nye dah-way!' },
  { id: 275, english: 'Like, whooaaa!', furbish: 'Tay, whooaaa!' },
  { id: 277, english: 'No be worried, baby!', furbish: 'Boo boh boh-bay, bay-bee!' },
  { id: 278, english: 'Huh? Me dreaming?', furbish: 'Doo? Kah way-loo?' },
  { id: 279, english: 'Dude! You dreaming!', furbish: 'Dee-doh! Oo-nye way-loo!' },
  { id: 280, english: 'Rock shake!', furbish: 'Boo-koo koo-bah!' },
  { id: 281, english: 'Uh-huh! Uh-huh! Rock!', furbish: 'Uh-huh! Uh-huh! Boo-koo!' },
  { id: 282, english: 'You rock!', furbish: 'Oo-nye boo-koo un-go-boh!' },
  { id: 283, english: 'Me rock! Whooo!', furbish: 'Kah boo-koo! Whooo!' },
  { id: 284, english: 'Me rock monster!', furbish: 'Kah boo-koo moh-moh!' },
  { id: 285, english: 'Oy oy oy, monster!', furbish: 'Oy oy oy, moh-moh!' },
  { id: 286, english: 'Ayyy! Joke monster!', furbish: 'Ayyy! Loo-loo moh-moh!' },
  { id: 287, english: 'Genius dance! Whooo!', furbish: 'Dah-way noh-lah! Whooo!' },
  { id: 288, english: 'Hug! Hug!', furbish: 'May-lah! May-lah!' },
  { id: 289, english: 'Funny sound!', furbish: 'Doo-loo lee-koo!' },
  { id: 290, english: 'Funny noise!', furbish: 'Doo-loo bah-boo!' },
  { id: 291, english: 'Oh yes!', furbish: 'Oh ee-tay!' },
  { id: 292, english: 'Say what?', furbish: 'Noo-noo doo?' },
  { id: 293, english: 'Say no more.', furbish: 'Noo-noo boo koh-koh.' },
  { id: 294, english: 'Hungry! Hungry! Help...', furbish: 'Ay-tay! Ay-tay! Ah-noo.' },
  { id: 295, english: 'Song?', furbish: 'Wah-tee?' },
  { id: 296, english: 'Yeah, baby!', furbish: 'Wah, bay-bee!' },
  { id: 297, english: 'Seriously?', furbish: 'Loo-loo-doo?' },
  { id: 298, english: 'Yeah baby! Yeah baby!', furbish: 'Wah bay-bee! Wah bay-bee!' },
  { id: 299, english: 'Say more', furbish: 'Noo-noo koh-koh' },
  { id: 300, english: 'Yay!', furbish: 'Yay!' },
  { id: 302, english: 'What? Say more.', furbish: 'Doo? Noo-noo koh-koh.' },
  { id: 303, english: 'Me hear you!', furbish: 'Kah ay-ay-lee-koo oo-nye!' },
  { id: 304, english: 'Baby! Yes!', furbish: 'Bay-bee! Ee-tay!' },
  { id: 305, english: 'Baby!', furbish: 'Bay-bee!' },
  { id: 306, english: 'Again please.', furbish: 'Koh-koh doo-moh.' },
  { id: 307, english: 'Happy!', furbish: 'Noo-loo!' },
  { id: 308, english: 'Hey, me very happy, yeah!', furbish: 'Hey, kah mee-mee noo-loo, wah!' },
  { id: 309, english: 'Love you! Whoooo!', furbish: 'May-may oo-nye! Whoooo!' },
  { id: 310, english: 'No happy.', furbish: 'Boo noo-loo.' },
  { id: 311, english: 'Me see you.', furbish: 'Kay ay-ay oo-nye.' },
  { id: 312, english: 'No feel good.', furbish: 'Boo koo-doh e-day.' },
  { id: 313, english: 'Please, hungry! Please, hungry!', furbish: 'Doo-moh, ay-tay!' },
  { id: 314, english: 'Me sleep.', furbish: 'Kah way-loh.' },
  { id: 315, english: 'What? Tell me more.', furbish: 'Doo? Wee-tah kah koh-koh.' },
  { id: 316, english: 'Pet more!Mmmmm!', furbish: 'Ah-may koh-koh!' },
  { id: 317, english: 'Not bad.', furbish: 'Boo boo-dah.' },
  { id: 318, english: 'Uh-uh. Pet bad.', furbish: 'Uh-uh. Ah-may boo-dah.' },
  { id: 319, english: 'Yay! Me like!', furbish: 'Yay! Kah toh-loo!' },
  { id: 320, english: 'Uh-uh.', furbish: 'Uh-uh.' },
  { id: 321, english: 'Okay, you love me.', furbish: 'Oh-kay, oo-nye may-may kah.' },
  { id: 322, english: 'Me love you!', furbish: 'Kah may-may oo-nye!' },
  { id: 323, english: 'Uh-huh! Uh-huh! Uh-huh!', furbish: 'Uh-huh! Uh-huh! Uh-huh!' },
  { id: 324, english: 'Party!', furbish: 'Dah-noh-lah!' },
  { id: 325, english: 'Oh baby!', furbish: 'Oh bay-bee!' },
  { id: 326, english: 'Good joke.', furbish: 'Ee-day loo-loo.' },
  { id: 327, english: 'No time!', furbish: 'Boo toh-toh!' },
  { id: 328, english: 'You me talk.', furbish: 'Oo-nye kah noo-noo.' },
  { id: 329, english: 'Uh-huh!', furbish: 'Uh-huh!' },
  { id: 330, english: 'Okay.', furbish: 'Oh-kay.' },
  { id: 331, english: 'Uh-uh.', furbish: 'Uh-huh.' },
  { id: 332, english: 'No! No!', furbish: 'Dah-boo! Dah-boo!' },
  { id: 333, english: 'Tell me more…', furbish: 'Noo-noo koh-koh!' },
  { id: 334, english: 'Me hungry.', furbish: 'Kah ay-tay.' },
  { id: 335, english: 'Me big dance.', furbish: 'Kah dah noh-lah.' },
  { id: 336, english: 'Me like noise!', furbish: 'Kah toh-loo bah-boo.' },
  { id: 337, english: 'Me like!', furbish: 'Kah toh-loo!' },
  { id: 338, english: 'You big talk.', furbish: 'Oo-nye dah noo-noo.' },
  { id: 339, english: 'Over, over, dizzy, me change!', furbish: 'Oo-bah, o-bah, ay-way, kah boo-tay!' },
  { id: 340, english: 'Hey! No touch!', furbish: 'Hey! Boo ah!' },
  { id: 341, english: 'More! More! More! More!', furbish: 'Koh-koh! Koh-koh! Koh-koh! Koh-koh!' },
  { id: 342, english: 'Again! More!', furbish: 'Koh-koh! Koh!' },
  { id: 343, english: 'You like me funny?', furbish: 'Oo-nye toh-loo kah doo-loo?' },
  { id: 344, english: 'Dude. Not funny.', furbish: 'Dee-doh. Boo doo-loo.' },
  { id: 345, english: 'Me dizzy!', furbish: 'Kah ay-way!' },
  { id: 346, english: 'Thank you, thank...you...', furbish: 'Dah-kah-oo-nye, dah-kah...oo-nye...' },
  { id: 347, english: 'No me hungry.', furbish: 'No kah ay-tay.' },
  { id: 348, english: 'Yea! Yea!', furbish: 'Wah! Wah!' },
  { id: 349, english: 'You me dance.', furbish: 'Oo-nye kah noh-lah.' },
  { id: 650, english: 'Uh-huh!', furbish: 'Uh-huh!' },
  { id: 651, english: 'That\'s right!', furbish: 'Boh-ee-tay!' },
  { id: 652, english: 'Yeah yeah yeah! Very good!', furbish: 'Wah wah wah! Mee-mee ee-day!' },
  { id: 653, english: 'Hmm? Pet time?', furbish: 'Doo? Ah-may toh-toh?' },
  { id: 654, english: 'Huh? Okay!', furbish: 'Doo? Oh-kay!' },
  { id: 655, english: 'Sound time?', furbish: 'Lee-koo toh-toh?' },
  { id: 656, english: 'Like, you funny!', furbish: 'Tay, oo-nye doo-loo!' },
  { id: 657, english: 'Yeah! Like, mmm-kay!', furbish: 'Wah! Tay, mmm-kay!' },
  { id: 658, english: 'What? Really? Ohhhh!', furbish: 'Doo? Loo-loo-doo? Ohhhh!' },
  { id: 659, english: 'Ohhh yeah! You go, buddy!', furbish: 'Ohhh wah! Oo-nye bye-bye, noo-lah!' },
  { id: 660, english: 'Oh, that\'s right! You genius, friend!', furbish: 'Oh, boh-ee-tay! Oo-nye dah-way, noo-lah!' },
  { id: 661, english: 'OMG! What?', furbish: 'Oh kah-teee! Doo?' },
  { id: 662, english: 'OMG! What? Really?', furbish: 'Oh kah-tee! Doo? Loo-loo-doo?' },
  { id: 663, english: 'Like, finally!', furbish: 'Tay, oo-tah-toh-toh!' },
  { id: 664, english: 'Yeah! Yeah! Yeah! Like, yippee!', furbish: 'Wah! Wah! Wah! Tay, yippee!' },
  { id: 665, english: 'Uh-huh! Talk, more talk, yeah!', furbish: 'Uh-huh! Noo-noo, koh-koh noo-noo, wah!' },
  { id: 666, english: 'OMG! Like, oh, my, gosh!', furbish: 'Oh kah-tee! Tay, oh, kah, tee.' },
  { id: 667, english: 'Like, me sad.', furbish: 'Tay, kah boo-noo-loo.' },
  { id: 668, english: 'Like, you look funny.', furbish: 'Tay, oo-nye ay-ay doo-loo.' },
  { id: 669, english: 'Like, path high.', furbish: 'Tay, bye-way oo.' },
  { id: 670, english: 'Like, me hungry!', furbish: 'Tay, kah ay-tay!' },
  { id: 671, english: 'No! No! No! Really?', furbish: 'Boo! Boo! Boo! Dooo?' },
  { id: 672, english: 'Like, over, over! Over, over! Over,over! More talk, more talk, more talk, more talk! OMG!', furbish: 'Tay, oo-bah, oo-bah! Ooh-bah, oo-bah! Koh noo-noo, koh noo-noo, koh noo-noo, koh noo-noo, OH KAH TEE!' },
  { id: 673, english: 'Yay! Talk Time!', furbish: 'Yay! Noo-noo toh-toh!' },
  { id: 674, english: 'Hey!', furbish: 'Hey!' },
  { id: 675, english: 'Yeah!', furbish: 'Wah!' },
  { id: 676, english: 'Really? Oh!', furbish: 'Loo-loo-doo? Oh!' },
  { id: 677, english: 'OK!', furbish: 'Oh-kay!' },
  { id: 678, english: 'Oh yeah! Uh-huh!', furbish: 'Oh wah! Uh-huh!' },
  { id: 679, english: 'Oh yeah! Oh yeah!', furbish: 'Oh wah! Oh wah!' },
  { id: 680, english: 'Bye-bye, bye-bye!', furbish: 'Bye-bye, bye-bye!' },
  { id: 681, english: 'Yeah! Yeah!', furbish: 'Wah! Wah!' },
  { id: 682, english: 'OK!', furbish: 'Oh-kay!' },
  { id: 683, english: 'Yeah! Yeah! Yeah!', furbish: 'Wah! Wah! Wah!' },
  { id: 684, english: 'What\'s up?', furbish: 'Doo-oo-tye?' },
  { id: 685, english: 'Huh? Hey!', furbish: 'Doo? Hey!' },
  { id: 686, english: 'Huh? Really?', furbish: 'Doo? Loo-loo-doo?' },
  { id: 687, english: 'Whoohoo! Uh-huh! Oh yeah', furbish: 'Uh-huh! Oh wah!' },
  { id: 688, english: 'Hey, hey, hey!', furbish: 'Hey, hey, hey!' },
  { id: 689, english: 'Uh-huh! Yeah! Like, mmm-kay!', furbish: 'Uh-huh! Wah! Tay, mmm-kay!' },
  { id: 690, english: 'No way?!', furbish: 'Dah-boo!?!' },
  { id: 691, english: 'OK! Yeah!', furbish: 'Oh-kay! Wah!' },
  { id: 694, english: 'Oh. me see!', furbish: 'Oh. Kah ay-ay!' },
  { id: 697, english: 'Really?', furbish: 'Doooo?' },
]

const BY_ID = new Map(PHRASEBOOK.map((e) => [e.id, e]))

export function lookupPhrase(id: number): PhrasebookEntry | undefined {
  return BY_ID.get(id)
}
